POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "colesturza",
  "email": "cole@email.com",
  "password": "password"
}

###

POST http://localhost:8080/tokens/authentication
Content-Type: application/json
Accept: application/json

{
  "username": "colesturza",
  "password": "password"
}

###

GET http://localhost:8080/users/colesturza
Authorization: Bearer 3kTCxouj3c7GPsMncUdIsbR7X37zY2Q1IiBNiDmnre8
Accept: application/json