spring:
  application:
    name: Stack Exchange
  config:
    import: optional:file:.env[.properties]

---
spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: ${MAIL_SERVER_USERNAME}
    password: ${MAIL_SERVER_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

logging:
  level:
    rip.opencasket: DEBUG
    org.hibernate: INFO